### ISSUE TITLE
Information on data processing progress and problem reporting : the vertebral labeling doesn’t work for several subject sessions

### ISSUE THREAD

**Issue by Mathilde-16** [Mathilde-16/STOP_MS_data#1]
Hello Pr Cohen-Adad,

Yesterday, I added a folder (BIDS-dataset) in the STOP_MS_data repository where I put data of the first two subjects in order to show you the BIDS organisation that seems to me to be the right one. Moreover, I added 2 folders, Segmentation_&_Vertebral-labeling_BIDS-data and ContrastAgnosticSeg_&_Vertebral-labeling_BIDS-data corresponding to the commands I ran thanks to sct_run_batch with batch scripts. There are also some of the output files (log files, qc…) to show you what I got. And these both folders corresponding also to the best of my different script versions.
Could you tell me, please, what do you think about them ?

In order to avoid to put many files in the repository, some necessary files for BIDS convention (e.g: dataset_description.json, participants.json,…) are not displayed here but they are, of course, presents in my real folders.

As you would expect, the vertebral labeling doesn’t work for several subject sessions. And especially for the second subject who has almost any sessions with vertebral labeling. 
Could we use the SPINEPS method you mentioned ? (I've already tried to install it and I think it worked)
Or the manual labeling using the sct_label_utils command ? 

Many thanks in advance for your help !

**Comment by jcohenadad** [comment]
i'm a bit confused by this issue-- the title says "Information on data processing progress and problem reporting : the vertebral labeling doesn’t work for several subject sessions #1", but the issue starts with data organization issue: "Yesterday, I added a folder (BIDS-dataset) in the STOP_MS_data repository where I put data of the first two subjects in order to show you the BIDS organisation that seems to me to be the right one"

in order to be able to help efficiently, please keep issues simple and specific. 

I let you reorganize this issue (split across multiple issues) and then i'll follow up

**Comment by jcohenadad** [comment]
stale issue-- closing
