### ISSUE TITLE
Unclear why smoothing is required-- comments needed

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#10]
https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L80-L81

**Comment by Mathilde-16** [comment]
My apologies for the delay of my answer, I was able to discuss with my team on Friday, I didn't see them the other days of this week.

Regarding the smoothing and also flattening commands, we have included them in the process for observing the final product and having a first view of the results. Now, we don't need these both commands but we keep them and comment out them (code lines below) for when we're going to present specific images following the analysis, because smoothing and flattening are very useful to produce nice looking images.

https://github.com/Mathilde-16/STOP_MS_data/blob/5a820c9f28c9f10e817adc326258bbfecb65296a/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L70-L75

**Comment by jcohenadad** [comment]
> Now, we don't need these both commands but we keep them and comment out them (code lines below) for when we're going to present specific images following the analysis, because smoothing and flattening are very useful to produce nice looking images.

I highly discourage commenting out code as it creates confusion for people reading the code. Code is either useful (in this case, uncomment it) or not useful (in this case, remove it entirely).

**Comment by Mathilde-16** [comment]
I understand, thank you. I've just removed code not useful in the [script](https://github.com/Mathilde-16/STOP_MS_data/commit/15784fdb20701ef35f2ba4cfcfd2a13a60939d2d).

**Comment by jcohenadad** [comment]
Fixed in 15784fdb20701ef35f2ba4cfcfd2a13a60939d2d
