### ISSUE TITLE
Unclear how the SPINEPS batch is supposed to be used-- and possible redundancy

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#15]
There are two batch scripts in this repos:
- [Script_SPINEPS.sh](https://github.com/Mathilde-16/STOP_MS_data/blob/main/Data_processing/SPINEPS_Vertebral_labeling/Script_SPINEPS.sh)
- https://github.com/Mathilde-16/STOP_MS_data/blob/main/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh

Which one should be run first? Also see #14 about improving the doc.

Also, the SPINEPS batch includes code to segment the cord:
https://github.com/Mathilde-16/STOP_MS_data/blob/47faee16341ef70a9ee507c46f1992de082466de/Data_processing/SPINEPS_Vertebral_labeling/Script_SPINEPS.sh#L95

But this is already done here:
https://github.com/Mathilde-16/STOP_MS_data/blob/47faee16341ef70a9ee507c46f1992de082466de/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L60

There is a lot of redundancy between these two scripts, and clarifying the doc is necessary before others can properly use the code.

**Comment by Mathilde-16** [comment]
Hi Julien, 

I've just committed and pushed the [last version of my script](https://github.com/Mathilde-16/STOP_MS_data/blob/31f10ad57b1df47a7c4d781753554917b97bf4ed/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh). I also removed the SPINEPS batch script as we are not going to use SPINEPS for the vertebral labeling. 

I'll also complete README (issue #14) so that you can understand how to use the script.

Thank you for your help!

**Comment by jcohenadad** [comment]
@Mathilde-16 please always refer to an issue (eg with 'Fixes #XX') in the commit, so the issue is cross-ref with the commit-- this is good git/github practice

**Comment by jcohenadad** [comment]
Irrelevant after of https://github.com/Mathilde-16/STOP_MS_data/pull/21
