### ISSUE TITLE
i suggest to use the latest sct_deepseg contrast-agnostic model

### ISSUE THREAD

**Issue by jcohenadad** [Mathilde-16/STOP_MS_data#7]
https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L64

**Comment by Mathilde-16** [comment]
Ok thanks.

Naive question : Does this mean that from now on I put aside [this script](https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh) ? Because I edited this script but maybe it wasn't necessary

**Comment by jcohenadad** [comment]
> Naive question : Does this mean that from now on I put aside [this script](https://github.com/Mathilde-16/STOP_MS_data/blob/c5bbd51d612161c7ff6d42657821202002fc3d41/Data_processing/Segmentation_%26_Vertebral-labeling_BIDS-data/Batch_script.sh) ? Because I edited this script but maybe it wasn't necessary

I don't know what this other script is about (as mentioned in https://github.com/Mathilde-16/STOP_MS_data/issues/3 the fact that there are multiple scripts lying around in this repos is too confusing)-- first, fix the duplication, and then I can give feedback on ONE version of the script

**Comment by Mathilde-16** [comment]
When I reorganized the folder, I kept these both scripts because they weren't duplication of each other, they represent two different ways to get the segmentation. One uses the sct_deepseg_sc command and the second one uses the contrast agnostic segmentation model thanks to the following lines :
https://github.com/Mathilde-16/STOP_MS_data/blob/cf9ac61bb15fafd56dfaa5ecc9229c5d097c5b37/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh#L60-L61
But if I understand correctly, I went about it the wrong way and I apologize if it was unclear. 

As you suggest to use the latest sct_deepseg contrast-agnostic model, I removed script using the sct_deepseg_sc command from the repository, in order to have one script in this repos.

**Comment by jcohenadad** [comment]
Yet, the two scripts end up having a large portion of the code that is duplicated, (eg: a diffchecker tool gives 78% duplication between the two scripts):

![image](https://github.com/Mathilde-16/STOP_MS_data/assets/2482071/7a19db9a-635f-4864-a99f-5af7116f2348)

If you wish to compare the effect of altering one or several parameter in the processing pipeline, a better and more sustainable approach is to introduce parametrization in your codebase, instead of duplicating the script and only altering a sub-section of the code. 

Useful resource about code duplication and parametrization:
- https://discourse.julialang.org/t/how-to-avoid-code-duplication-when-defining-a-function-with-multiple-methods/67681
- https://stackoverflow.com/questions/35162685/preventing-duplication-of-code-parametrize-a-single-function-or-create-two-sep
- https://wou.edu/las/cs/csclasses/cs161/Lectures/rulesofthumb.html
- https://mitcommlab.mit.edu/broad/commkit/coding-mindset/

**Comment by Mathilde-16** [comment]
Ok I understand. Thank you for these resources.

Now there is only one [script](https://github.com/Mathilde-16/STOP_MS_data/blob/24e106b3ddfe728378e7a3854cacdec42fd345aa/Data_processing/ContrastAgnosticSeg_%26_Vertebral-labeling_BIDS-data/Batch_script.sh) in the repos, I tried to use your ressources to compare the both segmentation methods.
(I couldn't ask my questions about the metrics today so, for now, I consider in the script we would like to compute only CSA)

**Comment by jcohenadad** [comment]
great! we can close this then— i’ll follow up in other issues

**Comment by Mathilde-16** [comment]
Perfect, many thanks for your help !
